version: '3.7'
services:
  prisma:
    image: prismagraphql/prisma:1.8
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            database: my_api
            host: host.docker.internal
            port: 5432
            user: postgres
            password: postgres
            migrations: true
    command: ["yarn", "start"]